### ISSUE TITLE
SIGSEGV when used with Python under WSL

### ISSUE THREAD

**Issue by Lucas-C** [jrfonseca/memtrail#3]
Hi!

I tried your project, but sadly I couldn't get far as it halts on startupt with a `SIGSEGV`:
```
$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.5 LTS"
$ python --version
Python 3.8.10
$ ./memtrail record python -c 'print("Hello world!")'
memtrail: limiting to 8532893696 bytes
SIGSEGV
```

**Comment by Lucas-C** [comment]
I switched my distro from WSL 1 to WSL 2 using `wsl --set-version Ubuntu-20.04 2` and now the problem is gone 😊

But thank you very much for the help,
and also for building this tool and for listing related software in your `README`!

**Comment by Lucas-C** [comment]
By the way, the `--report-maximum` option mentioned in the README for `memtrail report` does not seem to exist anymore

**Comment by jrfonseca** [comment]
Fixed.  It had been renamed as `--show-maximum`

**Comment by jrfonseca** [comment]
> But thank you very much for the help, 

You're welcome!

> and also for building this tool and for listing related software in your `README`!

Yeah, I normally get my personal projects to a point where they are minimally usable, but seldom improve them further unless there a very strong itch I need to scratch.  So I always like to provide a list of alternative tools -- many don't do the exact same thing -- but often have larger communities maintaining them.
